# Generated by Django 5.2 on 2025-10-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
