# Generated by Django 5.2.6 on 2025-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('publisher', 'Publisher'), ('editor', 'Editor'), ('reader', 'Reader')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('publisher', 'Publisher'), ('editor', 'Editor'), ('reader', 'Reader')], default='reader', max_length=32),
        ),
    ]
