# Generated by Django 5.2.6 on 2025-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='user_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='views',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
