# Generated by Django 5.2 on 2025-10-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
