# Generated by Django 5.2.6 on 2025-10-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_views_user_disliked_views_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
