# Generated by Django 5.2 on 2025-10-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_views_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('pended', 'Pending')], default='pending', max_length=20),
        ),
    ]
