# Generated by Django 5.2.6 on 2025-10-09 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='views',
            name='publication_publica_b2834f_idx',
        ),
        migrations.RemoveField(
            model_name='views',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='views',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='views',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='views',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='views',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_stats', to='publications.publication'),
        ),
        migrations.AlterField(
            model_name='views',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
