# Generated by Django 5.2 on 2025-10-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('pended', 'Pending')], default='draft', max_length=20),
        ),
    ]
