# Generated by Django 5.2.6 on 2025-10-10 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_remove_views_publication_publica_b2834f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publication',
            name='search_idx',
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated list of keywords (e.g., machine learning, AI)'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['title', 'abstract', 'keywords'], name='search_idx'),
        ),
    ]
