# Generated by Django 5.2.6 on 2025-10-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_remove_publication_search_idx_publication_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
