# Generated by Django 5.2.6 on 2025-10-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_rejection_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='video_file',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
